### ISSUE TITLE
Initialisierung

### ISSUE THREAD

**Issue by 71m024** [Meisterwerk-GmbH/core#1]
Bitte erstelle eine package und deploye es auf unserem packagist account (wie `bq-utils`).  
  
Danach erstellst du darin bitte unter dem namespace `Meisterwerk\Core` eine Klasse namens `ExceptionHandler`.  
Auf dieser Klasse übernimmst du dann die generische exception-handler Funktion, welche wir im shopify-bq Projekt verwenden.  

Danach bindest du dieses package in `shopify-bq` ein und ersetzt dort diese Funktion mit der aus diesem package.

**Comment by SaraLuethi** [comment]
@71m024 beides erledigt, auf einem branch im shopify-booqable projekt - kann man es issue closen?

**Comment by 71m024** [comment]
Sieht tip top aus, Danke 🎉  
Wenn wir in Zukunft Funktionen haben, die in mehereren Projekten nützlich wären. Kann man sie zu dieser Library hinzufügen.
