### ISSUE TITLE
Optimierung Exception-Handling

### ISSUE THREAD

**Issue by 71m024** [Meisterwerk-GmbH/core#2]
Es gab hier einen Fehler wo wir nicht sehen, warum die Fehler-Mail nicht versendet werden konnte: https://meisterwerk-gmbh.sentry.io/issues/3979162805/?project=6502102&referrer=regression_activity-email  

Bitte `handleWithCareInner()` so umbauen, dass der Fehler vom `$mailingCallback` zwischen die neue Exception und die ursprünglich Exception eingefügt wird.  
Es gibt dann folgende Verkettung wobei die untere Exception immer `$previous` von der oberen ist:  
  - neue Exception
  - Exception von `$mailingCallback`
  - Ursprüngliche Exception  
  
## Testing
Bitte gut testen ob das funktioniert. Kannst ja vermutlich einfach einen fehler werfen und den Mailhog ausschalten oder so...
  
## Systeme updaten
Zumal dieser Fehler jetzt erst auf Nuki vorgekommen ist würde ich die core-version nur mal dort updaten.

**Comment by SaraLuethi** [comment]
@71m024 ist in nuki eingebaut und core gemergt, kann ich den issue closen?
